[package]
name = "noclip"
version = "0.3.0"
authors = ["John M Archer <archer884@zoho.com"]
edition = "2021"
homepage = "https://github.com/archer884/noclip"
repository = "https://github.com/archer884/noclip"
documentation = "https://github.com/archer884/noclip"
license = "Unlicense"
description = """
A tool for copy/paste to and from stdin/stdout.
"""

[dependencies]
arboard = "2.1.1"
clap = { version = "3.2.7", features = ["derive"] }
# spispopd = { path = "../spispopd" }
thiserror = "1.0.31"
